name: assets_annotation_by_zpdl
description: annotaion for the assets_generator_by_zpdl package. Incluud only AssetsAnnotation class.
version: 1.1.3
homepage: https://github.com/zpdL-Studio/flutter_boilerplate_by_zpdl

environment:
  sdk: ">=2.18.6 <3.0.0"